# Generated by Django 5.0 on 2024-01-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
