# Generated by Django 5.0 on 2024-01-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_name', models.CharField(max_length=255)),
            ],
        ),
    ]
