# Generated by Django 5.0 on 2024-01-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
